name: deploy discord bots command

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/discord-bot/**"

jobs:
  deploy-command:
    runs-on: ubuntu-latest
    environment:
      name: discord-bot
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      # setup runtime
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: type check for discord bot
        run: pnpm run discord-bot -- typecheck

      - name: deploy discord bot commands
        run: pnpm run discord-bot -- deploy:commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
