name: deploy discord bots command

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/discord-bot/**"

jobs:
  deploy-command:
    runs-on: ubuntu-latest
    environment:
      name: discord-bot
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      # setup runtime
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: type check for discord bot
        run: pnpm run discord-bot -- typecheck

      - name: deploy discord bot commands
        run: pnpm run discord-bot -- deploy:commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
