name: Deploy DB

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/front/**"

jobs:
  deploy-db:
    name: deploy db
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: front
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      # setup
      - run: pnpm install --frozen-lockfile
      - run: pnpm run front -- build

      # Migration
      - name: Migration D1
        id: migration-d1
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        continue-on-error: true
        with:
          command: "d1 migrations apply ac-extreme-mercenaries-db --remote"
          apiToken: ${{ secrets.CLOUDFLARE_INTEGRATION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/front"
      - name: Upload Migration Error
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        with:
          name: migration-d1-error-log
          path: ./.config/.wrangler/logs/*
      - name: Migration Error
        if: ${{ steps.migration-d1.outcome == 'failure' }}
        run: |
          echo "error on d1 migration"
          exit 1
