name: test app

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "packages/front/**"
      - "packages/discord-bot/**"

jobs:
  test-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: front
            paths: "packages/front/**"
          - package: discord-bot
            paths: "packages/discord-bot/**"
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          filters: |
            package:
              - ${{ matrix.paths }}

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        if: steps.changes.outputs.package == 'true'

      - name: Setup pnpm
        if: steps.changes.outputs.package == 'true'
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        if: steps.changes.outputs.package == 'true'
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
        if: steps.changes.outputs.package == 'true'

      - run: pnpm run ${{ matrix.package }} -- build
        if: steps.changes.outputs.package == 'true'

      - run: pnpm run ${{ matrix.package }} -- typecheck
        if: steps.changes.outputs.package == 'true'

      - run: pnpm run ${{ matrix.package }} -- test
        if: steps.changes.outputs.package == 'true'
